repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix, --exit-zero]
        name: ruff (auto-fix)
        always_run: true
        description: "Auto-fix code style with ruff."
      - id: ruff-format
        args: [--fix]
        name: ruff (format)
        always_run: true
        description: "Auto-fix code style with ruff (format only)."
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--check]
        name: black check
        always_run: true
        description: "Check code style with black."

  - repo: local
    hooks:
      - id: export-ai-patch
        name: Export AI Patch
        entry: bash -c 'cp diagnostics/ai-patch-unapplied.patch exported-ai-patch.patch || true'
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
        description: "Export the AI patch for workflow artifacts even if patching fails."
