repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--check", "."]

  - repo: local
    hooks:
      - id: export-ai-patch
        name: Export AI Patch
        entry: bash -c 'cp diagnostics/ai-patch-unapplied.patch exported-ai-patch.patch || true'
        language: system
        always_run: true
        pass_filenames: false
        verbose: true
        description: "Export the AI patch for workflow artifacts even if patching fails."
