"""
PDF → CSV extractor for Itaú credit-card statements.

This module now contains the line parser that used to live in
``txt_to_csv``.  ``pdf_to_csv`` can therefore operate without importing the
old module.

CLI
---
python -m statement_refinery.pdf_to_csv input.pdf [--out output.csv]
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import logging
import re
import shutil
import sys
from datetime import date
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Final, Iterator, List, Optional

# ===== ENHANCED TEXT CLEANING FROM CODEX.PY =====
LEAD_SYM = ">@§$Z)_•*®«» "


def strip_pua(s: str) -> str:
    """Remove Private Use Area glyphs (icons)"""
    return re.sub("[\ue000-\uf8ff]", "", s)


def clean_line(raw: str) -> str:
    """Enhanced line cleaning from codex.py"""
    raw = strip_pua(raw)
    raw = raw.lstrip(LEAD_SYM).replace("_", " ")
    raw = re.sub(r"\s{2,}", " ", raw)
    return raw.strip()


# Amount below which transactions are considered adjustments
ADJUSTMENT_THRESHOLD: Final = Decimal("0.30")

# ===== CORE REGEX PATTERNS =====

# Enhanced patterns combining best of both parsers
RE_DOM_STRICT: Final = re.compile(
    r"^[~g]*\s*(?P<date>\d{1,3}/\d{1,2})\s+"  # Allow 3 digits for day (from codex.py)
    r"(?P<desc>.+?)\s+"
    r"(?P<amt>-?\d{1,3}(?:\.\d{3})*,\d{2})\s*(?:R\$)?(?:\s+.*)?$"
)

RE_DOM_TOLERANT: Final = re.compile(
    r"^(?P<date>\d{1,3}/\d{1,2})\s+(.+?)\s+(?P<amt>-?\d{1,3}(?:\.\d{3})*,\d{2})$"  # Allow 3 digits for day
)

# Codex.py's flexible domestic pattern for fallback
RE_DOM_FLEXIBLE: Final = re.compile(
    r"^(?P<date>\d{1,3}/\d{1,2})\s+(?P<desc>.+?)\s+(?P<amt>[-\d.,]+)$"
)

RE_FX_LINE1: Final = re.compile(
    r"^(?P<date>\d{2}/\d{2})\s+(?P<descr>.+?)\s+"
    r"(?P<orig>-?\d{1,3}(?:\.\d{3})*,\d{2})\s+"
    r"(?P<brl>-?\d{1,3}(?:\.\d{3})*,\d{2})$"
)

RE_FX_LINE2: Final = re.compile(
    r"(USD|EUR|GBP|JPY|CHF|CAD|AUD)\s+([\d,\.]+)\s*=\s*([\d,\.]+)\s*BRL(?:\s+(.+))?"
)

# ===== ENHANCED PATTERNS FOR IMPROVED COVERAGE =====

# Better payment detection from codex.py
RE_PAYMENT_ROBUST: Final = re.compile(
    r"^(?P<date>\d{1,3}/\d{1,2}(?:/\d{4})?)\s+PAGAMENTO.*?(?P<amt>-?\s*[\d.,]+)\s*$",
    re.I,
)

# Improved date pattern with tolerance
RE_DATE_TOLERANT: Final = re.compile(r"(?P<d>\d{1,3})/(?P<m>\d{1,2})(?:/(?P<y>\d{4}))?")

# Better installment patterns from codex.py
RE_INSTALLMENT_ROBUST: Final = re.compile(
    r"(\d{1,2})\s*/\s*(\d{1,2})|(\d{1,2})\s*x\s*R\$|(\d{1,2})\s*de\s*(\d{1,2})", re.I
)

# Currency conversion rate lines
RE_CURRENCY_CONVERSION: Final = re.compile(
    r"Dólar\s+de\s+Conversão\s+R\$\s+(?P<rate1>\d+,\d{2})(?:\s+Dólar\s+de\s+Conversão\s+R\$\s+(?P<rate2>\d+,\d{2}))?",
    re.I,
)

# International transaction with city and amounts
RE_INTL_TRANSACTION: Final = re.compile(
    r"^(?P<city>\w+)\s+(?P<orig_amt>\d{1,3}(?:\.\d{3})*,\d{2})\s+(?P<currency>[A-Z]{3})\s+(?P<brl_amt>\d{1,3}(?:\.\d{3})*,\d{2})(?:\s+(?P<desc>.+))?$"
)

# Payment summary lines
RE_PAYMENT_SUMMARY: Final = re.compile(
    r"^(?P<type>[A-Z])\s+(?P<desc>[\w\s]+)\s+-\s+(?P<amount>\d{1,3}(?:\.\d{3})*,\d{2})$"
)

# Transaction reference codes
RE_TRANSACTION_CODE: Final = re.compile(
    r"^(?P<code>[A-Z]{2,3})\s+-\s+(?P<ref>\d+\s+\d+\s+[A-Z0-9]+)\s+(?P<date>\d{2}/\d{2}/\d{4})\s+(?P<details>[\w\s]+)$"
)

# Fee information lines
RE_FEE_INFO: Final = re.compile(
    r"^(?P<desc>(?:valor\s+)?(?:juros|multa|encargo|tarifa)[\w\s]*)\s+(?P<amount>\d{1,3}(?:\.\d{3})*,\d{2})$",
    re.I,
)

# More specific patterns from failed line analysis
RE_INTEREST_VALUE: Final = re.compile(
    r"^Valor\s+juros\s+(?P<amount>\d{1,3}(?:\.\d{3})*,\d{2})$", re.I
)

RE_CET_RATE: Final = re.compile(
    r"^CET\s+da\s+compra\s+parcelada\s+(?P<monthly>\d+,\d{2})\s+%\s+am\s+(?P<annual>\d{1,3},\d{2})\s+%\s+aa$",
    re.I,
)

RE_INSTALLMENT_VALUE: Final = re.compile(
    r"^Valor\s+da\s+parcela\s+(?P<amount>\d{1,3}(?:\.\d{3})*,\d{2})$", re.I
)

# === NEW: CATEGORY-SPECIFIC PATTERNS FOR FITNESS OPTIMIZATION ===

# Domestic merchant categories (SUPERMERCADO, FARMÁCIA, RESTAURANTE, POSTO, etc.)
RE_DOMESTIC_CATEGORY: Final = re.compile(
    r"(?P<cat>SUPERMERCADO|FARM[ÁA]CIA|RESTAURANTE|POSTO|COMBUST[IÍ]VEL|TRANSPORTE|LOJA|VAREJO|SHOPPING|PADARIA|EDUCACAO|EDUCAÇÃO|ESCOLA|FACULDADE|UNIVERSIDADE|PETSHOP|PET SHOP|HOSPITAL|CLINICA|CLÍNICA|SA[ÚU]DE|FARMACIA|FARMÁCIA|DROGARIA|DROG[ÁA]RIA|TELEFONE|CELULAR|INTERNET|ASSINATURA|STREAMING|ENTRETENIMENTO|LAZER|VIAGEM|PASSAGEM|HOTEL|HOSPEDAGEM|TURISMO|SEGURO|SEGUROS|SERVI[ÇC]O|SERVIÇOS|ENCARGO|TARIFA|JUROS|MULTA|IMPOSTO|TAXA|GOVERNO|TRIBUTO|IPTU|IPVA|DPVAT|LICENCIAMENTO|ALUGUEL|CONDOMINIO|CONDOMÍNIO|ENERGIA|LUZ|ÁGUA|AGUA|GAS|GÁS|TELECOM|PLANO|ODONTO|DENTISTA|CONSULTA|EXAME|LABORAT[ÓO]RIO|FATURA|RECARGA|CARTÃO|CARTAO|TRANSFER[ÊE]NCIA|PIX|TED|DOC|DEP[ÓO]SITO|SAQUE|CREDITO|CRÉDITO|DEBITO|DÉBITO|PAGAMENTO|PAGTO|COMPRA|VENDA|ESTORNO|AJUSTE|AJUSTES|CASHBACK|BONUS|BÔNUS|REEMBOLSO|RESTITUI[ÇC][AÃ]O|DEVOLU[ÇC][AÃ]O|ANTECIPA[ÇC][AÃ]O|PARCELA|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCELAS|PARCELAMENTO|PARCELADO|PARCEL