name: CI (internal-only)

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      force-evolve:
        description: "Run AI loop even when tests are green"
        required: false
        default: "false"
  schedule:
    - cron: "0 3 * * *"

jobs:
  evolve:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write        # so we can push

    steps:
      # --- Step 1: built-in checkout (no external action) -------------
      - name: Checkout self
        run: |
          git init .
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git fetch --depth=1 origin "$GITHUB_SHA"
          git checkout -qf "$GITHUB_SHA"

      # --- Step 2: install Python -------------------------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5   # <-- REMOVE THIS LINE if policy bans it
        # If even setup-python is disallowed, uncomment the shell fallback below
        # run: |
        #   sudo apt-get update -y
        #   sudo apt-get install -y python3 python3-venv python3-pip
        #   python3 -m pip install --upgrade pip

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run self-healing AI loop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FORCE_EVOLVE:   ${{ github.event.inputs.force-evolve }}
        run: |
          python .github/tools/ai_patch_loop.py

      # --- Step 4: push results ---------------------------------------
      - name: Push commits produced by loop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
 
          # -----------------------------------------------------------------
          # Ensure 'origin' uses the CI token, so `git push` authenticates.
          # checkout@v4 does this automatically, but if it was replaced or
          # modified earlier we guarantee it here.
          # -----------------------------------------------------------------
          git remote set-url origin \
            "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
 
          # ----------------------------------------------------------
          # figure out the branch we should push to
          # ----------------------------------------------------------
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
            TARGET_BRANCH="$GITHUB_HEAD_REF"   # e.g. feature/my-branch
          else
            TARGET_BRANCH="${GITHUB_REF#refs/heads/}" # e.g. main
          fi

          # When Actions checks out a specific commit we sit on a detached HEAD.
          # Create/overwrite the branch so we can push to it.
          git checkout -B "$TARGET_BRANCH"

          # Only push if there is at least one new commit compared to remote.
          if git rev-parse --verify "origin/$TARGET_BRANCH" >/dev/null 2>&1; then
            RANGE="origin/$TARGET_BRANCH..HEAD"
          else
            RANGE="HEAD"   # first push of a brand-new branch
          fi

          if git log --oneline $RANGE | grep .; then
            git push --force-with-lease origin "$TARGET_BRANCH"
          else
            echo "No new commits to push."
          fi
