name: CI

on: [push, pull_request]

jobs:
  test-and-auto-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # we need history for git apply / commit

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (incl dev + openai)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests once
        id: testrun
        run: |
          pytest -q --maxfail=25 || echo "failures=true" >> $GITHUB_OUTPUT

      - name: AI-Patch loop (one iteration)
        if: steps.testrun.outputs.failures == 'true'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python .github/tools/ai_patch.py

      - name: Push commit (if any)
        if: env.GITHUB_TOKEN != ''
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 AUTO-FIX via CI"
