name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'   # daily smoke run

env:
  OPENAI_MODEL: gpt-4.1
  MAX_TOKENS_PER_RUN: '1000000'   # 1 M-token budget
  MAX_ATTEMPTS: '3'
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  GITHUB_TOKEN:   ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}

jobs:
  static:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN:   ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dev deps

        run: pip install -e '.[dev]'

      - name: Ruff lint
        run: ruff check .

      - name: Black format check
        run: black --check .

      - name: MyPy type check
        run: mypy src/

  tests-evolve:
    needs: static
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN:   ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dev deps

        run: pip install -e '.[dev]'

      # run tests once, capture failure but don't abort
      - name: PyTest + Coverage
        id: tests
        continue-on-error: true
        run: pytest -ra -vv --cov=statement_refinery --cov-report=term-missing --cov-fail-under=90

      # auto-patch loop if tests failed or FORCE_EVOLVE=1
      - name: Evolve patch loop
        if: steps.tests.outcome == 'failure' || env.FORCE_EVOLVE == '1'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.PERSONAL_ACCESS_TOKEN_CLASSIC }}

        run: python .github/tools/evolve.py

      # confirm everything green after patch
      - name: Re-run tests
        if: always()
        run: pytest -ra -vv --cov=statement_refinery --cov-report=term-missing --cov-fail-under=90

      - name: Check parser accuracy
        if: always()
        run: python scripts/check_accuracy.py
