name: CI (internal-only)

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      force-evolve:
        description: "Run AI loop even when tests are green"
        required: false
        default: "false"
  schedule:
    - cron: "0 3 * * *"

jobs:
  evolve:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write        # so we can push

    steps:
      # --- Step 1: built-in checkout (no external action) -------------
      - name: Checkout self
        run: |
          git init .
          git remote add origin "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
          git fetch --depth=1 origin "$GITHUB_SHA"
          git checkout -qf "$GITHUB_SHA"

      # --- Step 2: install Python -------------------------------------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5   # <-- REMOVE THIS LINE if policy bans it
        # If even setup-python is disallowed, uncomment the shell fallback below
        # run: |
        #   sudo apt-get update -y
        #   sudo apt-get install -y python3 python3-venv python3-pip
        #   python3 -m pip install --upgrade pip

      - name: Install project (dev)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run self-healing AI loop
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FORCE_EVOLVE:   ${{ github.event.inputs.force-evolve }}
        run: |
          python .github/tools/ai_patch_loop.py

      # --- Step 4: push results ---------------------------------------
      - name: Push commits produced by loop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          if ! git diff --quiet origin/${GITHUB_REF#refs/heads/}; then
            git push --force-with-lease
          else
            echo "No new commits to push."
          fi
