name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * *'   # daily smoke run

env:
  OPENAI_MODEL: gpt-4.1
  MAX_TOKENS_PER_RUN: '1000000'   # 1 M-token budget
  MAX_ATTEMPTS: '3'

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dev deps

        run: pip install -e ".[dev]"

      - name: Ruff lint
        run: ruff check .

      - name: Black format check
        run: black --check .

      - name: MyPy type check
        run: mypy src/

  tests-evolve:
    needs: static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dev deps

        run: pip install -e ".[dev]"

      # run tests once, capture failure but don't abort
      - name: PyTest + Coverage
        id: tests
        continue-on-error: true
        run: pytest -q --cov=statement_refinery --cov-fail-under=90

      # auto-patch loop if tests failed
      - name: Evolve patch loop
        if: steps.tests.outcome == 'failure'
        run: python .github/tools/evolve.py

      # confirm everything green after patch
      - name: Re-run tests
        if: always()
        run: pytest -q --cov=statement_refinery --cov-fail-under=90
